RHOAIENG-72: Specify numeric UID in Dockerfiles
This resolves the

```
Error: container has runAsNonRoot and image has non-numeric user (rhods), cannot verify user is non-root
```

issue.

OpenShift (by default)
runs images under a random user id and the root user group.

See https://access.redhat.com/documentation/cn/openshift_container_platform/4.15/html/images/creating-images#use-uid_create-images

(cherry picked from commit f51ed22c969d79ed9dca92e8a314beb89b13ffc7)